In [1]:
from google.colab import files
import pandas as pd
import io
import sys
from termcolor import colored, cprint

In [13]:
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['marital_status.csv']))

Saving marital_status.csv to marital_status.csv

In [17]:
df = pd.read_csv(io.BytesIO(uploaded['marital_status.csv']))

In [18]:
df

,m15+,mnever,mmarried,mseparated,mwidowed,mdivorced,f15+,fnever,fmarried,fseparated,fwidowed,fdivorced
0,1423,401,863,36,10,113,1456,396,873,15,65,107
1,1099,402,535,8,18,136,1644,694,496,11,91,352
2,1532,559,810,18,64,81,1608,437,709,37,177,248
3,1946,673,1132,19,0,122,1959,564,1035,36,13,311
4,1262,366,753,59,27,57,1290,329,776,9,92,84
...,...,...,...,...,...,...,...,...,...,...,...,...
253,1757,595,993,11,7,151,2039,641,1018,14,117,249
254,1854,532,1203,0,73,46,1606,333,1174,8,31,60
255,0,0,0,0,0,0,5,0,0,0,5,0
256,0,0,0,0,0,0,0,0,0,0,0,0
257,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
df["never"] = df["mnever"] + df["fnever"]
df["married"] = df["mmarried"] + df["fmarried"]
df["separated"] = df["mseparated"] + df["fseparated"]
df["widowed"] = df["mwidowed"] + df["fwidowed"]
df["divorced"] = df["mdivorced"] + df["fdivorced"]
df = df[["married", "widowed", "divorced", "separated", "never"]]

In [20]:
df

     married  widowed  divorced  separated  never
0       1736       75       220         51    797
1       1031      109       488         19   1096
2       1519      241       329         55    996
3       2167       13       433         55   1237
4       1529      119       141         68    695
..       ...      ...       ...        ...    ...
253     2011      124       400         25   1236
254     2377      104       106          8    865
255        0        5         0          0      0
256        0        0         0          0      0
257        0        0         0          0      0

[258 rows x 5 columns]

In [23]:
df.to_csv('marital_status.csv')